export const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;

export const dummySlider = [
  {
    name: `Simple -${"\n"}Rock Chair`,
    imageLink: "https://z9d7c4u6.rocketcdn.me/wp-content/uploads/2017/01/slider-main-demo-1.jpg",
  },
  {
    name: `Simple -${"\n"}Rock Chair`,
    imageLink: "https://z9d7c4u6.rocketcdn.me/wp-content/uploads/2017/01/slider-main-demo-2.jpg",
  },
];

export const countryList = [
  {
    id: 2,
    sortname: "AL",
    name: "Albania",
    phonecode: 355,
    language_code: "sq",
  },
  {
    id: 3,
    sortname: "DZ",
    name: "Algeria",
    phonecode: 213,
    language_code: "ar",
  },
  {
    id: 4,
    sortname: "AS",
    name: "American Samoa",
    phonecode: 1684,
    language_code: "sm",
  },
  {
    id: 5,
    sortname: "AD",
    name: "Andorra",
    phonecode: 376,
    language_code: "it",
  },
  {
    id: 6,
    sortname: "AO",
    name: "Angola",
    phonecode: 244,
    language_code: "pt",
  },
  {
    id: 7,
    sortname: "AI",
    name: "Anguilla",
    phonecode: 1264,
    language_code: "in",
  },
  {
    id: 8,
    sortname: "AQ",
    name: "Antarctica",
    phonecode: 0,
    language_code: "en",
  },
  {
    id: 9,
    sortname: "AG",
    name: "Antigua And Barbuda",
    phonecode: 1268,
    language_code: "in",
  },
  {
    id: 10,
    sortname: "AR",
    name: "Argentina",
    phonecode: 54,
    language_code: "es",
  },
  {
    id: 11,
    sortname: "AM",
    name: "Armenia",
    phonecode: 374,
    language_code: "hy",
  },
  {
    id: 12,
    sortname: "AW",
    name: "Aruba",
    phonecode: 297,
    language_code: "nl",
  },
  {
    id: 13,
    sortname: "AU",
    name: "Australia",
    phonecode: 61,
    language_code: "en",
  },
  {
    id: 14,
    sortname: "AT",
    name: "Austria",
    phonecode: 43,
    language_code: "of",
  },
  {
    id: 15,
    sortname: "AZ",
    name: "Azerbaijan",
    phonecode: 994,
    language_code: "az",
  },
  {
    id: 16,
    sortname: "BS",
    name: "Bahamas The",
    phonecode: 1242,
    language_code: "in",
  },
  {
    id: 17,
    sortname: "BH",
    name: "Bahrain",
    phonecode: 973,
    language_code: "ar",
  },
  {
    id: 18,
    sortname: "BD",
    name: "Bangladesh",
    phonecode: 880,
    language_code: "bn",
  },
  {
    id: 19,
    sortname: "BB",
    name: "Barbados",
    phonecode: 1246,
    language_code: "in",
  },
  {
    id: 20,
    sortname: "BY",
    name: "Belarus",
    phonecode: 375,
    language_code: "be",
  },
  {
    id: 21,
    sortname: "BE",
    name: "Belgium",
    phonecode: 32,
    language_code: "fr",
  },
  {
    id: 22,
    sortname: "BZ",
    name: "Belize",
    phonecode: 501,
    language_code: "in",
  },
  {
    id: 23,
    sortname: "BJ",
    name: "Benin",
    phonecode: 229,
    language_code: "fr",
  },
  {
    id: 24,
    sortname: "BM",
    name: "Bermuda",
    phonecode: 1441,
    language_code: "in",
  },
  {
    id: 25,
    sortname: "BT",
    name: "Bhutan",
    phonecode: 975,
    language_code: "dz",
  },
  {
    id: 26,
    sortname: "BO",
    name: "Bolivia",
    phonecode: 591,
    language_code: "es",
  },
  {
    id: 27,
    sortname: "BA",
    name: "Bosnia and Herzegovina",
    phonecode: 387,
    language_code: "bs",
  },
  {
    id: 28,
    sortname: "BW",
    name: "Botswana",
    phonecode: 267,
    language_code: "in",
  },
  {
    id: 29,
    sortname: "BV",
    name: "Bouvet Island",
    phonecode: 0,
    language_code: "no",
  },
  {
    id: 30,
    sortname: "BR",
    name: "Brazil",
    phonecode: 55,
    language_code: "pt",
  },
  {
    id: 31,
    sortname: "IO",
    name: "British Indian Ocean Territory",
    phonecode: 246,
    language_code: "in",
  },
  {
    id: 32,
    sortname: "BN",
    name: "Brunei",
    phonecode: 673,
    language_code: "ms",
  },
  {
    id: 33,
    sortname: "BG",
    name: "Bulgaria",
    phonecode: 359,
    language_code: "bg",
  },
  {
    id: 34,
    sortname: "BF",
    name: "Burkina Faso",
    phonecode: 226,
    language_code: "fr",
  },
  {
    id: 35,
    sortname: "BI",
    name: "Burundi",
    phonecode: 257,
    language_code: "fr",
  },
  {
    id: 36,
    sortname: "KH",
    name: "Cambodia",
    phonecode: 855,
    language_code: "km",
  },
  {
    id: 37,
    sortname: "CM",
    name: "Cameroon",
    phonecode: 237,
    language_code: "fr",
  },
  {
    id: 38,
    sortname: "CA",
    name: "Canada",
    phonecode: 1,
    language_code: "en",
  },
  {
    id: 39,
    sortname: "CV",
    name: "Cape Verde",
    phonecode: 238,
    language_code: "-",
  },
  {
    id: 40,
    sortname: "KY",
    name: "Cayman Islands",
    phonecode: 1345,
    language_code: "in",
  },
  {
    id: 41,
    sortname: "CF",
    name: "Central African Republic",
    phonecode: 236,
    language_code: "fr",
  },
  {
    id: 42,
    sortname: "TD",
    name: "Chad",
    phonecode: 235,
    language_code: "fr",
  },
  {
    id: 43,
    sortname: "CL",
    name: "Chile",
    phonecode: 56,
    language_code: "es",
  },
  {
    id: 44,
    sortname: "CN",
    name: "China",
    phonecode: 86,
    language_code: "zh-ha",
  },
  {
    id: 45,
    sortname: "CX",
    name: "Christmas Island",
    phonecode: 61,
    language_code: "in",
  },
  {
    id: 46,
    sortname: "CC",
    name: "Cocos (Keeling) Islands",
    phonecode: 672,
    language_code: "in",
  },
  {
    id: 47,
    sortname: "CO",
    name: "Colombia",
    phonecode: 57,
    language_code: "es",
  },
  {
    id: 48,
    sortname: "KM",
    name: "Comoros",
    phonecode: 269,
    language_code: "ar",
  },
  {
    id: 49,
    sortname: "CG",
    name: "Congo",
    phonecode: 242,
    language_code: "fr",
  },
  {
    id: 50,
    sortname: "CD",
    name: "Congo The Democratic Republic Of The",
    phonecode: 242,
    language_code: "fr",
  },
  {
    id: 51,
    sortname: "CK",
    name: "Cook Islands",
    phonecode: 682,
    language_code: "in",
  },
  {
    id: 52,
    sortname: "CR",
    name: "Costa Rica",
    phonecode: 506,
    language_code: "es",
  },
  {
    id: 53,
    sortname: "CI",
    name: "Cote D'Ivoire (Ivory Coast)",
    phonecode: 225,
    language_code: "fr",
  },
  {
    id: 54,
    sortname: "HR",
    name: "Croatia (Hrvatska)",
    phonecode: 385,
    language_code: "hr",
  },
  {
    id: 55,
    sortname: "CU",
    name: "Cuba",
    phonecode: 53,
    language_code: "es",
  },
  {
    id: 56,
    sortname: "CY",
    name: "Cyprus",
    phonecode: 357,
    language_code: "el",
  },
  {
    id: 57,
    sortname: "CZ",
    name: "Czech Republic",
    phonecode: 420,
    language_code: "cs",
  },
  {
    id: 58,
    sortname: "DK",
    name: "Denmark",
    phonecode: 45,
    language_code: "da",
  },
  {
    id: 59,
    sortname: "DJ",
    name: "Djibouti",
    phonecode: 253,
    language_code: "fr",
  },
  {
    id: 60,
    sortname: "DM",
    name: "Dominica",
    phonecode: 1767,
    language_code: "in",
  },
  {
    id: 61,
    sortname: "DO",
    name: "Dominican Republic",
    phonecode: 1809,
    language_code: "es",
  },
  {
    id: 62,
    sortname: "TP",
    name: "East Timor",
    phonecode: 670,
    language_code: "pt",
  },
  {
    id: 63,
    sortname: "EC",
    name: "Ecuador",
    phonecode: 593,
    language_code: "es",
  },
  {
    id: 64,
    sortname: "EG",
    name: "Egypt",
    phonecode: 20,
    language_code: "ar",
  },
  {
    id: 65,
    sortname: "SV",
    name: "El Salvador",
    phonecode: 503,
    language_code: "es",
  },
  {
    id: 66,
    sortname: "GQ",
    name: "Equatorial Guinea",
    phonecode: 240,
    language_code: "es",
  },
  {
    id: 67,
    sortname: "ER",
    name: "Eritrea",
    phonecode: 291,
    language_code: "ti",
  },
  {
    id: 68,
    sortname: "EE",
    name: "Estonia",
    phonecode: 372,
    language_code: "and",
  },
  {
    id: 69,
    sortname: "ET",
    name: "Ethiopia",
    phonecode: 251,
    language_code: "am",
  },
  {
    id: 70,
    sortname: "XA",
    name: "External Territories of Australia",
    phonecode: 61,
    language_code: "in",
  },
  {
    id: 71,
    sortname: "FK",
    name: "Falkland Islands",
    phonecode: 500,
    language_code: "in",
  },
  {
    id: 72,
    sortname: "FO",
    name: "Faroe Islands",
    phonecode: 298,
    language_code: "fo",
  },
  {
    id: 73,
    sortname: "FJ",
    name: "Fiji Islands",
    phonecode: 679,
    language_code: "in",
  },
  {
    id: 74,
    sortname: "FI",
    name: "Finland",
    phonecode: 358,
    language_code: "fi",
  },
  {
    id: 75,
    sortname: "FR",
    name: "France",
    phonecode: 33,
    language_code: "fr",
  },
  {
    id: 76,
    sortname: "GF",
    name: "French Guiana",
    phonecode: 594,
    language_code: "fr",
  },
  {
    id: 77,
    sortname: "PF",
    name: "French Polynesia",
    phonecode: 689,
    language_code: "fr",
  },
  {
    id: 78,
    sortname: "TF",
    name: "French Southern Territories",
    phonecode: 0,
    language_code: "fr",
  },
  {
    id: 79,
    sortname: "GA",
    name: "Gabon",
    phonecode: 241,
    language_code: "fr",
  },
  {
    id: 80,
    sortname: "GM",
    name: "Gambia The",
    phonecode: 220,
    language_code: "in",
  },
  {
    id: 81,
    sortname: "GE",
    name: "Georgia",
    phonecode: 995,
    language_code: "ka",
  },
  {
    id: 82,
    sortname: "DE",
    name: "Germany",
    phonecode: 49,
    language_code: "of",
  },
  {
    id: 83,
    sortname: "GH",
    name: "Ghana",
    phonecode: 233,
    language_code: "in",
  },
  {
    id: 84,
    sortname: "GI",
    name: "Gibraltar",
    phonecode: 350,
    language_code: "in",
  },
  {
    id: 85,
    sortname: "GR",
    name: "Greece",
    phonecode: 30,
    language_code: "el",
  },
  {
    id: 86,
    sortname: "GL",
    name: "Greenland",
    phonecode: 299,
    language_code: "kl",
  },
  {
    id: 87,
    sortname: "GD",
    name: "Grenada",
    phonecode: 1473,
    language_code: "in",
  },
  {
    id: 88,
    sortname: "GP",
    name: "Guadeloupe",
    phonecode: 590,
    language_code: "fr",
  },
  {
    id: 89,
    sortname: "GU",
    name: "Guam",
    phonecode: 1671,
    language_code: "in",
  },
  {
    id: 90,
    sortname: "GT",
    name: "Guatemala",
    phonecode: 502,
    language_code: "es",
  },
  {
    id: 91,
    sortname: "XU",
    name: "Guernsey and Alderney",
    phonecode: 44,
    language_code: "in",
  },
  {
    id: 92,
    sortname: "GN",
    name: "Guinea",
    phonecode: 224,
    language_code: "fr",
  },
  {
    id: 93,
    sortname: "GW",
    name: "Guinea-Bissau",
    phonecode: 245,
    language_code: "pt",
  },
  {
    id: 94,
    sortname: "GY",
    name: "Guyana",
    phonecode: 592,
    language_code: "in",
  },
  {
    id: 95,
    sortname: "HT",
    name: "Haiti",
    phonecode: 509,
    language_code: "fr",
  },
  {
    id: 96,
    sortname: "HM",
    name: "Heard and McDonald Islands",
    phonecode: 0,
    language_code: "in",
  },
  {
    id: 97,
    sortname: "HN",
    name: "Honduras",
    phonecode: 504,
    language_code: "es",
  },
  {
    id: 98,
    sortname: "HK",
    name: "Hong Kong S.A.R.",
    phonecode: 852,
    language_code: "en",
  },
  {
    id: 99,
    sortname: "HU",
    name: "Hungary",
    phonecode: 36,
    language_code: "hu",
  },
  {
    id: 100,
    sortname: "IS",
    name: "Iceland",
    phonecode: 354,
    language_code: "is",
  },
  {
    id: 101,
    sortname: "IN",
    name: "India",
    phonecode: 91,
    language_code: "en",
  },
  {
    id: 102,
    sortname: "ID",
    name: "Indonesia",
    phonecode: 62,
    language_code: "id",
  },
  {
    id: 103,
    sortname: "IR",
    name: "Iran",
    phonecode: 98,
    language_code: "fa",
  },
  {
    id: 104,
    sortname: "IQ",
    name: "Iraq",
    phonecode: 964,
    language_code: "ar",
  },
  {
    id: 105,
    sortname: "IE",
    name: "Ireland",
    phonecode: 353,
    language_code: "in",
  },
  {
    id: 106,
    sortname: "IL",
    name: "Israel",
    phonecode: 972,
    language_code: "hey",
  },
  {
    id: 107,
    sortname: "IT",
    name: "Italy",
    phonecode: 39,
    language_code: "it",
  },
  {
    id: 108,
    sortname: "JM",
    name: "Jamaica",
    phonecode: 1876,
    language_code: "in",
  },
  {
    id: 109,
    sortname: "JP",
    name: "Japan",
    phonecode: 81,
    language_code: "ja",
  },
  {
    id: 110,
    sortname: "XJ",
    name: "Jersey",
    phonecode: 44,
    language_code: "in",
  },
  {
    id: 111,
    sortname: "JO",
    name: "Jordan",
    phonecode: 962,
    language_code: "ar",
  },
  {
    id: 112,
    sortname: "KZ",
    name: "Kazakhstan",
    phonecode: 7,
    language_code: "ru",
  },
  {
    id: 113,
    sortname: "KE",
    name: "Kenya",
    phonecode: 254,
    language_code: "sw",
  },
  {
    id: 114,
    sortname: "KI",
    name: "Kiribati",
    phonecode: 686,
    language_code: "in",
  },
  {
    id: 115,
    sortname: "KP",
    name: "North Korea",
    phonecode: 850,
    language_code: "ko",
  },
  {
    id: 116,
    sortname: "KR",
    name: "South Korea",
    phonecode: 82,
    language_code: "ko",
  },
  {
    id: 117,
    sortname: "KW",
    name: "Kuwait",
    phonecode: 965,
    language_code: "ar",
  },
  {
    id: 118,
    sortname: "KG",
    name: "Kyrgyzstan",
    phonecode: 996,
    language_code: "ky",
  },
  {
    id: 119,
    sortname: "LA",
    name: "Laos",
    phonecode: 856,
    language_code: "lo",
  },
  {
    id: 120,
    sortname: "LV",
    name: "Latvia",
    phonecode: 371,
    language_code: "lv",
  },
  {
    id: 121,
    sortname: "LB",
    name: "Lebanon",
    phonecode: 961,
    language_code: "ar",
  },
  {
    id: 122,
    sortname: "LS",
    name: "Lesotho",
    phonecode: 266,
    language_code: "in",
  },
  {
    id: 123,
    sortname: "LR",
    name: "Liberia",
    phonecode: 231,
    language_code: "in",
  },
  {
    id: 124,
    sortname: "LY",
    name: "Libya",
    phonecode: 218,
    language_code: "ar",
  },
  {
    id: 125,
    sortname: "LI",
    name: "Liechtenstein",
    phonecode: 423,
    language_code: "of",
  },
  {
    id: 126,
    sortname: "LT",
    name: "Lithuania",
    phonecode: 370,
    language_code: "lt",
  },
  {
    id: 127,
    sortname: "LU",
    name: "Luxembourg",
    phonecode: 352,
    language_code: "lb",
  },
  {
    id: 128,
    sortname: "MO",
    name: "Macau S.A.R.",
    phonecode: 853,
    language_code: "pt",
  },
  {
    id: 129,
    sortname: "MK",
    name: "Macedonia",
    phonecode: 389,
    language_code: "mk",
  },
  {
    id: 130,
    sortname: "MG",
    name: "Madagascar",
    phonecode: 261,
    language_code: "fr",
  },
  {
    id: 131,
    sortname: "MW",
    name: "Malawi",
    phonecode: 265,
    language_code: "in",
  },
  {
    id: 132,
    sortname: "MY",
    name: "Malaysia",
    phonecode: 60,
    language_code: "ms",
  },
  {
    id: 133,
    sortname: "MV",
    name: "Maldives",
    phonecode: 960,
    language_code: "dv",
  },
  {
    id: 134,
    sortname: "ML",
    name: "Mali",
    phonecode: 223,
    language_code: "fr",
  },
  {
    id: 135,
    sortname: "MT",
    name: "Malta",
    phonecode: 356,
    language_code: "in",
  },
  {
    id: 136,
    sortname: "XM",
    name: "Man (Isle of)",
    phonecode: 44,
    language_code: "in",
  },
  {
    id: 137,
    sortname: "MH",
    name: "Marshall Islands",
    phonecode: 692,
    language_code: "in",
  },
  {
    id: 138,
    sortname: "MQ",
    name: "Martinique",
    phonecode: 596,
    language_code: "fr",
  },
  {
    id: 139,
    sortname: "MR",
    name: "Mauritania",
    phonecode: 222,
    language_code: "ar",
  },
  {
    id: 140,
    sortname: "MU",
    name: "Mauritius",
    phonecode: 230,
    language_code: "en",
  },
  {
    id: 141,
    sortname: "YT",
    name: "Mayotte",
    phonecode: 269,
    language_code: "fr",
  },
  {
    id: 142,
    sortname: "MX",
    name: "Mexico",
    phonecode: 52,
    language_code: "es",
  },
  {
    id: 143,
    sortname: "FM",
    name: "Micronesia",
    phonecode: 691,
    language_code: "in",
  },
  {
    id: 144,
    sortname: "MD",
    name: "Moldova",
    phonecode: 373,
    language_code: "ro",
  },
  {
    id: 145,
    sortname: "MC",
    name: "Monaco",
    phonecode: 377,
    language_code: "fr",
  },
  {
    id: 146,
    sortname: "MN",
    name: "Mongolia",
    phonecode: 976,
    language_code: "mn",
  },
  {
    id: 147,
    sortname: "MS",
    name: "Montserrat",
    phonecode: 1664,
    language_code: "in",
  },
  {
    id: 148,
    sortname: "MA",
    name: "Morocco",
    phonecode: 212,
    language_code: "fr",
  },
  {
    id: 149,
    sortname: "MZ",
    name: "Mozambique",
    phonecode: 258,
    language_code: "pt",
  },
  {
    id: 150,
    sortname: "MM",
    name: "Myanmar",
    phonecode: 95,
    language_code: "my",
  },
  {
    id: 151,
    sortname: "NA",
    name: "Namibia",
    phonecode: 264,
    language_code: "in",
  },
  {
    id: 152,
    sortname: "NR",
    name: "Nauru",
    phonecode: 674,
    language_code: "in",
  },
  {
    id: 153,
    sortname: "NP",
    name: "Nepal",
    phonecode: 977,
    language_code: "born",
  },
  {
    id: 154,
    sortname: "AN",
    name: "Netherlands Antilles",
    phonecode: 599,
    language_code: "nl",
  },
  {
    id: 155,
    sortname: "NL",
    name: "Netherlands The",
    phonecode: 31,
    language_code: "nl",
  },
  {
    id: 156,
    sortname: "NC",
    name: "New Caledonia",
    phonecode: 687,
    language_code: "fr",
  },
  {
    id: 157,
    sortname: "NZ",
    name: "New Zealand",
    phonecode: 64,
    language_code: "en",
  },
  {
    id: 158,
    sortname: "NI",
    name: "Nicaragua",
    phonecode: 505,
    language_code: "es",
  },
  {
    id: 159,
    sortname: "NE",
    name: "Niger",
    phonecode: 227,
    language_code: "fr",
  },
  {
    id: 160,
    sortname: "NG",
    name: "Nigeria",
    phonecode: 234,
    language_code: "in",
  },
  {
    id: 161,
    sortname: "NU",
    name: "Niue",
    phonecode: 683,
    language_code: "in",
  },
  {
    id: 162,
    sortname: "NF",
    name: "Norfolk Island",
    phonecode: 672,
    language_code: "in",
  },
  {
    id: 163,
    sortname: "MP",
    name: "Northern Mariana Islands",
    phonecode: 1670,
    language_code: "in",
  },
  {
    id: 164,
    sortname: "NO",
    name: "Norway",
    phonecode: 47,
    language_code: "nb",
  },
  {
    id: 165,
    sortname: "OM",
    name: "Oman",
    phonecode: 968,
    language_code: "ar",
  },
  {
    id: 166,
    sortname: "PK",
    name: "Pakistan",
    phonecode: 92,
    language_code: "in",
  },
  {
    id: 167,
    sortname: "PW",
    name: "Palau",
    phonecode: 680,
    language_code: "en",
  },
  {
    id: 168,
    sortname: "PS",
    name: "Palestinian Territory Occupied",
    phonecode: 970,
    language_code: "ar",
  },
  {
    id: 169,
    sortname: "PA",
    name: "Panama",
    phonecode: 507,
    language_code: "es",
  },
  {
    id: 170,
    sortname: "PG",
    name: "Papua new Guinea",
    phonecode: 675,
    language_code: "in",
  },
  {
    id: 171,
    sortname: "PY",
    name: "Paraguay",
    phonecode: 595,
    language_code: "es",
  },
  {
    id: 172,
    sortname: "PE",
    name: "Peru",
    phonecode: 51,
    language_code: "es",
  },
  {
    id: 173,
    sortname: "PH",
    name: "Philippines",
    phonecode: 63,
    language_code: "en",
  },
  {
    id: 174,
    sortname: "PN",
    name: "Pitcairn Island",
    phonecode: 0,
    language_code: "in",
  },
  {
    id: 175,
    sortname: "PL",
    name: "Poland",
    phonecode: 48,
    language_code: "pl",
  },
  {
    id: 176,
    sortname: "PT",
    name: "Portugal",
    phonecode: 351,
    language_code: "pt",
  },
  {
    id: 177,
    sortname: "PR",
    name: "Puerto Rico",
    phonecode: 1787,
    language_code: "in",
  },
  {
    id: 178,
    sortname: "QA",
    name: "Qatar",
    phonecode: 974,
    language_code: "ar",
  },
  {
    id: 179,
    sortname: "RE",
    name: "Reunion",
    phonecode: 262,
    language_code: "in",
  },
  {
    id: 180,
    sortname: "RO",
    name: "Romania",
    phonecode: 40,
    language_code: "ro",
  },
  {
    id: 181,
    sortname: "RU",
    name: "Russia",
    phonecode: 70,
    language_code: "ru",
  },
  {
    id: 182,
    sortname: "RW",
    name: "Rwanda",
    phonecode: 250,
    language_code: "rw",
  },
  {
    id: 183,
    sortname: "SH",
    name: "Saint Helena",
    phonecode: 290,
    language_code: "in",
  },
  {
    id: 184,
    sortname: "KN",
    name: "Saint Kitts And Nevis",
    phonecode: 1869,
    language_code: "in",
  },
  {
    id: 185,
    sortname: "LC",
    name: "Saint Lucia",
    phonecode: 1758,
    language_code: "in",
  },
  {
    id: 186,
    sortname: "PM",
    name: "Saint Pierre and Miquelon",
    phonecode: 508,
    language_code: "fr",
  },
  {
    id: 187,
    sortname: "VC",
    name: "Saint Vincent And The Grenadines",
    phonecode: 1784,
    language_code: "in",
  },
  {
    id: 188,
    sortname: "WS",
    name: "Samoa",
    phonecode: 684,
    language_code: "in",
  },
  {
    id: 189,
    sortname: "SM",
    name: "San Marino",
    phonecode: 378,
    language_code: "it",
  },
  {
    id: 190,
    sortname: "ST",
    name: "Sao Tome and Principe",
    phonecode: 239,
    language_code: "pt",
  },
  {
    id: 191,
    sortname: "SA",
    name: "Saudi Arabia",
    phonecode: 966,
    language_code: "ar",
  },
  {
    id: 192,
    sortname: "SN",
    name: "Senegal",
    phonecode: 221,
    language_code: "fr",
  },
  {
    id: 193,
    sortname: "RS",
    name: "Serbia",
    phonecode: 381,
    language_code: "sr",
  },
  {
    id: 194,
    sortname: "SC",
    name: "Seychelles",
    phonecode: 248,
    language_code: "en",
  },
  {
    id: 195,
    sortname: "SL",
    name: "Sierra Leone",
    phonecode: 232,
    language_code: "in",
  },
  {
    id: 196,
    sortname: "SG",
    name: "Singapore",
    phonecode: 65,
    language_code: "ta",
  },
  {
    id: 197,
    sortname: "SK",
    name: "Slovakia",
    phonecode: 421,
    language_code: "sk",
  },
  {
    id: 198,
    sortname: "SI",
    name: "Slovenia",
    phonecode: 386,
    language_code: "sl",
  },
  {
    id: 199,
    sortname: "XG",
    name: "Smaller Territories of the UK",
    phonecode: 44,
    language_code: "in",
  },
  {
    id: 200,
    sortname: "SB",
    name: "Solomon Islands",
    phonecode: 677,
    language_code: "in",
  },
  {
    id: 201,
    sortname: "SO",
    name: "Somalia",
    phonecode: 252,
    language_code: "so",
  },
  {
    id: 202,
    sortname: "ZA",
    name: "South Africa",
    phonecode: 27,
    language_code: "en",
  },
  {
    id: 203,
    sortname: "GS",
    name: "South Georgia",
    phonecode: 0,
    language_code: "in",
  },
  {
    id: 204,
    sortname: "SS",
    name: "South Sudan",
    phonecode: 211,
    language_code: "in",
  },
  {
    id: 205,
    sortname: "ES",
    name: "Spain",
    phonecode: 34,
    language_code: "ast",
  },
  {
    id: 206,
    sortname: "LK",
    name: "Sri Lanka",
    phonecode: 94,
    language_code: "if",
  },
  {
    id: 207,
    sortname: "SD",
    name: "Sudan",
    phonecode: 249,
    language_code: "in",
  },
  {
    id: 208,
    sortname: "SR",
    name: "Suriname",
    phonecode: 597,
    language_code: "nl",
  },
  {
    id: 209,
    sortname: "SJ",
    name: "Svalbard And Jan Mayen Islands",
    phonecode: 47,
    language_code: "no",
  },
  {
    id: 210,
    sortname: "SZ",
    name: "Swaziland",
    phonecode: 268,
    language_code: "in",
  },
  {
    id: 211,
    sortname: "SE",
    name: "Sweden",
    phonecode: 46,
    language_code: "sv",
  },
  {
    id: 212,
    sortname: "CH",
    name: "Switzerland",
    phonecode: 41,
    language_code: "fr",
  },
  {
    id: 213,
    sortname: "SY",
    name: "Syria",
    phonecode: 963,
    language_code: "ar",
  },
  {
    id: 214,
    sortname: "TW",
    name: "Taiwan",
    phonecode: 886,
    language_code: "zh-ha",
  },
  {
    id: 215,
    sortname: "TJ",
    name: "Tajikistan",
    phonecode: 992,
    language_code: "tg",
  },
  {
    id: 216,
    sortname: "TZ",
    name: "Tanzania",
    phonecode: 255,
    language_code: "in",
  },
  {
    id: 217,
    sortname: "TH",
    name: "Thailand",
    phonecode: 66,
    language_code: "th",
  },
  {
    id: 218,
    sortname: "TG",
    name: "Togo",
    phonecode: 228,
    language_code: "fr",
  },
  {
    id: 219,
    sortname: "TK",
    name: "Tokelau",
    phonecode: 690,
    language_code: "tkl",
  },
  {
    id: 220,
    sortname: "TO",
    name: "Tonga",
    phonecode: 676,
    language_code: "in",
  },
  {
    id: 221,
    sortname: "TT",
    name: "Trinidad And Tobago",
    phonecode: 1868,
    language_code: "in",
  },
  {
    id: 222,
    sortname: "TN",
    name: "Tunisia",
    phonecode: 216,
    language_code: "ar",
  },
  {
    id: 223,
    sortname: "TR",
    name: "Turkey",
    phonecode: 90,
    language_code: "tr",
  },
  {
    id: 224,
    sortname: "TM",
    name: "Turkmenistan",
    phonecode: 7370,
    language_code: "tk",
  },
  {
    id: 225,
    sortname: "TC",
    name: "Turks And Caicos Islands",
    phonecode: 1649,
    language_code: "in",
  },
  {
    id: 226,
    sortname: "TV",
    name: "Tuvalu",
    phonecode: 688,
    language_code: "in",
  },
  {
    id: 227,
    sortname: "UG",
    name: "Uganda",
    phonecode: 256,
    language_code: "in",
  },
  {
    id: 228,
    sortname: "UA",
    name: "Ukraine",
    phonecode: 380,
    language_code: "uk",
  },
  {
    id: 229,
    sortname: "AE",
    name: "United Arab Emirates",
    phonecode: 971,
    language_code: "ar",
  },
  {
    id: 230,
    sortname: "GB",
    name: "United Kingdom",
    phonecode: 44,
    language_code: "en",
  },
  {
    id: 231,
    sortname: "US",
    name: "United States",
    phonecode: 1,
    language_code: "en",
  },
  {
    id: 232,
    sortname: "UM",
    name: "United States Minor Outlying Islands",
    phonecode: 1,
    language_code: "en",
  },
  {
    id: 233,
    sortname: "UY",
    name: "Uruguay",
    phonecode: 598,
    language_code: "es",
  },
  {
    id: 234,
    sortname: "UZ",
    name: "Uzbekistan",
    phonecode: 998,
    language_code: "uz",
  },
  {
    id: 235,
    sortname: "VU",
    name: "Vanuatu",
    phonecode: 678,
    language_code: "en",
  },
  {
    id: 236,
    sortname: "VA",
    name: "Vatican City State (Holy See)",
    phonecode: 39,
    language_code: "it",
  },
  {
    id: 237,
    sortname: "VE",
    name: "Venezuela",
    phonecode: 58,
    language_code: "es",
  },
  {
    id: 238,
    sortname: "VN",
    name: "Vietnam",
    phonecode: 84,
    language_code: "vi",
  },
  {
    id: 239,
    sortname: "VG",
    name: "Virgin Islands (British)",
    phonecode: 1284,
    language_code: "en",
  },
  {
    id: 240,
    sortname: "VI",
    name: "Virgin Islands (US)",
    phonecode: 1340,
    language_code: "en",
  },
  {
    id: 241,
    sortname: "WF",
    name: "Wallis And Futuna Islands",
    phonecode: 681,
    language_code: "fr",
  },
  {
    id: 242,
    sortname: "EH",
    name: "Western Sahara",
    phonecode: 212,
    language_code: "fr",
  },
  {
    id: 243,
    sortname: "YE",
    name: "Yemen",
    phonecode: 967,
    language_code: "ar",
  },
  {
    id: 244,
    sortname: "YU",
    name: "Yugoslavia",
    phonecode: 38,
    language_code: "en",
  },
  {
    id: 245,
    sortname: "ZM",
    name: "Zambia",
    phonecode: 260,
    language_code: "en",
  },
  {
    id: 246,
    sortname: "ZW",
    name: "Zimbabwe",
    phonecode: 263,
    language_code: "en",
  },
];

export function shuffle(originalArray) {
  var array = [].concat(originalArray);
  var currentIndex = array.length,
    temporaryValue,
    randomIndex;

  // While there remain elements to shuffle...
  while (0 !== currentIndex) {
    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;

    // And swap it with the current element.
    temporaryValue = array[currentIndex];
    array[currentIndex] = array[randomIndex];
    array[randomIndex] = temporaryValue;
  }

  return array;
}
